"""English strings. This is the fallback — any key missing elsewhere resolves here."""

M = {
    # ── words ─────────────────────────────────────────────────────────────
    'word.tables': 'Tables',
    'word.columns': 'Columns',
    'word.areas': 'Areas',
    'word.layer': 'Layer',
    'word.schema': 'Schema',
    'word.fkeys': 'FKs',
    'word.pk': 'primary key',
    'word.fk': 'foreign key',
    'word.unique': 'unique',
    'word.kind': 'Kind',
    'word.content': 'Content',
    'word.basis': 'Source',
    'word.notation': 'Notation',
    'word.meaning': 'Meaning',
    'word.lines': 'Lines',
    'word.added': '[new]',
    'word.source': 'source',
    'word.extended': 'extended',
    'word.existing': 'existing',
    'word.external': 'external',
    'word.solid': 'solid line',
    'word.dashed': 'dashed line (brown)',
    'word.semicircle': 'semicircle',
    'word.crowfoot': 'crow\'s foot / plain end',
    'word.child_table': 'Child table',
    'word.parent_table': 'Parent table',
    'word.delete_rule': 'Delete rule',
    'word.src_side': 'Source (ref schema)',
    'word.dst_side': 'Target (public schema)',
    'word.priority': 'Pri.',
    'word.item': 'Item',
    'word.target': 'Target',
    'word.current': 'Current state',
    'word.action': 'Action needed',
    'word.proposed': 'Proposed design',
    'word.actual_table': 'Actual table',
    'word.applied': 'Applied',
    'word.reason': 'Reason',
    'word.fig_no': '[Fig. {n}]',
    'word.area_other': '{schema} other',
    'word.font_body': 'body',
    'word.font_mono': 'monospace',

    # ── column table ──────────────────────────────────────────────────────
    'col.name': 'Column',
    'col.type': 'Type',
    'col.default': 'Default',
    'col.key': 'Key / Ref',
    'col.desc': 'Description',

    # ── HTML schema reference ─────────────────────────────────────────────
    'html.single_db': '(single database)',
    'html.fig_zoom': '— click to open at full size',
    'html.meta_area_layer': 'Area {area} · layer {layer}',
    'html.role': 'Role',
    'html.constraints': 'Constraints · indexes ({n})',
    'html.rows_note': 'rows ≈ is an estimate from statistics',
    'html.toc': 'Contents',
    'html.db_tables': 'DB: {db} · tables {n}',
    'html.overall': 'Overall structure',
    'html.overview_cap': '{title} — structure overview (tables {n} · relationships only)',
    'html.area_cap': '{name} — area detail ERD',
    'html.full_cap': '{title} — full detail ERD (every table · every column)',
    'html.appendix': 'Appendix. Full detail ERD',
    'html.appendix_desc': 'Every table and column on a single sheet. '
                          'On screen, click to enlarge.',
    'html.zoomhint': 'click or press Esc to close',

    # ── ERD diagram ───────────────────────────────────────────────────────
    'erd.ref_of': '[ref] {area} · {role}',
    'erd.readonly_src': '{schema} (read only)',
    'erd.group_label': '{schema} schema · {code} {name}',
    'erd.node_desc': '[{layer}] [area {code} {area}] {note}',
    'erd.lg_new': 'new table',
    'erd.lg_ext': 'existing table · columns added',
    'erd.lg_src': 'source in the ref schema',
    'erd.lg_fk': 'foreign key (FK) · label = child column : parent column',
    'erd.lg_etl': 'ETL load flow (not an FK)',
    'erd.lg_hop': 'crossing (the line hops over)',
    'erd.sub_overview': 'color = layer / grouping = schema and area',
    'erd.sub_full': 'tables {tables} · columns {columns} · foreign keys {fks}',
    'erd.sub_etl': ' · ETL flows {n}',
    'erd.sub_area': '{schema} schema · tables {n}',
    'erd.sub_ext': ' · external references {n}',
    'verify.label_table': 'label↔table',
    'verify.thru': 'line↔table',
    'verify.label_x': 'label↔label',
    'verify.v_overlap': 'vertical overlap',
    'verify.h_overlap': 'horizontal overlap',
    'verify.tolerated': '{n}(tolerated)',
    'verify.na': 'n/a',
    'verify.warn': '  [warn] must be 0: {list}',

    # ── docx document ─────────────────────────────────────────────────────
    'docx.doc_name': 'Document',
    'docx.ch1': '1. Overview',
    'docx.ch1_1': '1.1 Purpose',
    'docx.purpose': 'Presents the table structure and relationships of the target '
                    'database as an ERD. It is generated by reading the live schema, '
                    'so the diagram cannot drift from the database.',
    'docx.ch1_2': '1.2 Scope',
    'docx.scope_in': 'Included: structure, columns and relationships of {n} tables, '
                     'plus the schema and layer breakdown.',
    'docx.scope_out': 'Excluded: migration procedures, API specifications, screen design.',
    'docx.ch1_3': '1.3 Basis',
    'docx.sources_note': 'This ERD was generated by reading the live database and its '
                         'DDL. Table names, column names, types and constraints '
                         'therefore match the actual schema.',
    'docx.src_infoschema': 'actual values for tables, columns, types, PKs, FKs and delete rules',
    'docx.src_comment': 'table and column comments',
    'docx.src_comment_d': 'first source for descriptions',
    'docx.src_orm': 'ORM model comments',
    'docx.src_orm_d': 'descriptions for columns with no comment',
    'docx.ch1_4': '1.4 Notation',
    'docx.by_color': '{code} (by color)',
    'docx.nt_new': 'newly created table',
    'docx.nt_ext': 'existing table · columns added',
    'docx.nt_src': 'external source · read only',
    'docx.nt_added': 'column added in this revision',
    'docx.nt_solid': 'foreign key (FK) · label reads "child column : parent column"',
    'docx.nt_dashed': 'ETL load flow — a data flow, not an FK',
    'docx.nt_hop': 'marks a line hopping over another (not a connection)',
    'docx.nt_card': 'the N side (child) / the 1 side (parent) of a relationship',
    'docx.ch2': '2. Schema and layer structure',
    'docx.ch2_intro': 'In the diagram below, color indicates the layer and grouping '
                      'indicates the schema and functional area.',
    'docx.fig_overview': '{title} — relationship overview',
    'docx.ch2_1': '2.1 Full ERD',
    'docx.ch2_1_intro': 'Every column and description of all {n} tables on one sheet. '
                        'It is reduced in print and hard to read there, so use the '
                        'per-area ERDs in chapter 3, or the original image, for detail.',
    'docx.fig_full': '{title} — full (columns and descriptions)',
    'docx.ch3': '3. ERD by area',
    'docx.ch3_intro': 'Each area is shown with all its columns and descriptions. '
                      'Referenced tables outside the area appear as condensed boxes '
                      'with a grey border.',
    'docx.ch3_area': '3.{no} Area {code} · {name} ({schema} schema · tables {n})',
    'docx.fig_area': 'Area {code} · {name}',
    'docx.ch4': '4. Table roles and column descriptions',
    'docx.ch4_intro': 'Tables {tables} · columns {columns} in total. In the Kind column, '
                      'PK is the primary key, FK a foreign key, and [new] marks a column '
                      'added in this revision.',
    'docx.ch4_area': '4.{no} Area {code} · {name}',
    'docx.ch5': '5. Relationships',
    'docx.ch5_1': '5.1 Foreign keys (FK)',
    'docx.ch5_1_intro': '{n} in total. Where the delete rule is CASCADE, deleting the '
                        'parent deletes the child rows with it; where it is SET NULL, '
                        'only the reference is cleared and the row remains.',
    'docx.ch5_2': '5.2 ETL load flows',
    'docx.ch5_2_intro': 'These are data flows, not FKs. The ref schema is read only, so '
                        'no physical constraint can be placed on it.',
    'docx.ch6': '6. Design proposal vs. what was built',
    'docx.ch6_intro': 'The table names in the design proposal differ from those in the '
                      'actual DDL. Each item is matched up below to show how it was '
                      'actually implemented.',
    'docx.ch7': '7. Open items and decisions still needed',
    'docx.ch7_intro': 'This ERD defines structure; structure alone does not make the '
                      'system run. The items below need a decision outside the schema '
                      'before their values can be filled in.',

    # ── common column descriptions ────────────────────────────────────────
    'common.id': 'row identifier (PK)',
    'common.seq': 'row identifier (PK)',
    'common.uuid': 'row identifier (UUID)',
    'common.created_at': 'created at',
    'common.updated_at': 'updated at',
    'common.deleted_at': 'deleted at (soft delete)',
    'common.created_by': 'created by',
    'common.updated_by': 'updated by',
    'common.loaded_at': 'loaded at',
    'common.started_at': 'started at',
    'common.ended_at': 'ended at',
    'common.status': 'status',
    'common.note': 'note',
    'common.remark': 'note',
    'common.sort_order': 'sort order',
    'common.rank': 'rank',
    'common.version': 'version',
    'common.is_active': 'active flag',
    'common.active_yn': 'active flag',

    # ── errors ────────────────────────────────────────────────────────────
    'err.no_conn': 'No database connection configured. Set one of the two.',
    'err.no_conn_db': "'container:user:db'        # via docker",
    'err.no_schema_tables': 'No tables left to draw. {path} is empty, or ERD_EXCLUDE removed everything.',
    'err.no_tables': 'Not a single table could be read. '
                     'Check ERD_DB / ERD_PSQL / ERD_SCHEMAS / ERD_EXCLUDE.',
    'err.font_env': 'the font set in {env} cannot be used: {path}',
    'err.font_none': 'No {kind} font found. Run install.sh, or set {env} yourself.\n'
                     '  Looked in: {looked}',
    'err.merge_usage': 'usage: python3 merge_schemas.py <label> <label> …',
    'err.merge_missing': '{path} does not exist. Run introspect.py with '
                         'ERD_LABEL={label} first.',
    'err.no_sql_dir': 'no DDL directory: {path}  (set it with ERD_SQL_DIR)',
    'err.spec_no_area': '{path} defines areas, but none of them name a table that exists.',
    'err.spec_layer': 'layer {key} is malformed: {value}\n'
                      '  expected [fill, header, border, label] with #rrggbb colors',
    'err.spec_json': '{path} is not valid JSON: {err}',
    'err.stale_figs': '{n} diagrams are older than {path}: {list}\n'
                      '  They depict an earlier schema — the document would show one thing '
                      'in the tables and another in the figures.\n'
                      '  Run build_erd.py again, or set ERD_STALE=warn to embed them as they are.',
    'err.pg_too_old': 'PostgreSQL {found} is too old — {need} or later is required.\n'
                      '  Older servers do not carry a subquery alias into row_to_json, so '
                      'every value would come back empty, and the foreign-key query needs '
                      'WITH ORDINALITY.',
    'err.query_failed': 'could not read {what} from the database: {err}\n'
                        '  Nothing was written. A run that read only part of the schema '
                        'produces a document that looks complete and is not.',
    'err.query_truncated': 'the result stopped in the middle of a row',

    # ── progress output ───────────────────────────────────────────────────
    'log.query_fail': '  [warn] database query failed: {err}',
    'log.query_incomplete': '  [warn] could not be read: {list} — the document is missing '
                            'exactly those parts',
    'log.spec_empty': '  [warn] areas with no usable table, skipped: {list}',
    'log.spec_dup': '  [warn] {n} tables appear in more than one area — kept in the first: {list}',
    'log.spec_missing': '  [warn] spec names {n} tables that are not in the schema: {list}',
    'log.introspected': 'tables {tables} · columns {columns} · FKs {fks} → {path}',
    'log.desc_from_db': '  column descriptions filled from DB comments: {n}/{total}',
    'log.desc_rest': '  → fill in the rest with merge_desc.py',
    'log.dup_names': '  {n} table names exist in more than one schema — keyed as schema.table: {list}',
    'log.exclude_rule': '  exclude rule: {rule}',
    'log.fk_dropped': '  dropped FKs that point outside the target: {n}',
    'log.per_schema': '  [{schema}] {n}',
    'log.doc_missing': '  [warn] ERD_DOC_HTML document not found: {path}',
    'log.doc_inherited': '  column descriptions carried over from {name}: {n}',
    'log.by_source': 'columns by description source:',
    'log.no_desc': 'columns still without a description:',
    'log.desc_ambiguous': '  [warn] {n} keys name a table that exists more than once and '
                          'were ignored — use the qualified key: {list}',
    'log.merge_part': '  {label}  tables {tables} · columns {columns}',
    'log.merge_total': 'total  tables {tables} · columns {columns} · FKs {fks} → {path}',
    'log.ddl_parsed': 'tables {n} → {path}',
    'log.ddl_no_db': '  {n} tables are only referenced, never defined in the DDL — drawn as name-only boxes (set ERD_DB/ERD_PSQL to fill them in): {list}',
    'log.ddl_row': 'cols {columns}{added} FK {fks}  · {note}',
    'log.ddl_added': ' (+{n} new)',
    'log.graphml': 'GraphML  nodes {nodes} · relationships {edges}  → {name}',
    'log.png_overview': 'PNG  overview → {name} {size}',
    'log.png_full': 'PNG  full ERD → {name} {size}',
    'log.png_area': 'PNG  area {code} {name} ({n} + {ext} refs) → {file}  {size}',
    'log.scale_down': '    [note] {name}: diagram too large, scale lowered to {s}×',
    'log.overlap_at': '      overlap: at {a}  [{s0}~{s1}] vs [{t0}~{t1}]',
    'log.verify': '    verify {name}: {report}',
    'log.verify_log_fail': '  [warn] ERD_VERIFY_LOG could not be written, the figures are '
                           'still there: {path} — {err}',
    'log.html_done': 'HTML  tables {tables} · areas {areas} · figures {figs}  '
                     '{mb}MB → {name}',
    'log.html_missing': '  [warn] areas with no diagram: {n} ({list})  '
                        '→ run build_erd.py first',
    'log.stale_figs': '  [warn] embedding {n} diagrams older than the schema '
                      '(ERD_STALE): {list}',
    'log.docx_saved': 'saved: {name} ({kb} KB)',
    'log.figs_missing': '  [warn] diagrams not found, left out of the document: '
                        '{n} ({list})  → run build_erd.py first',
}
